export const tasks= [
  { _id: 'a1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'b1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'c1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'd1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'f1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'g1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'h1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'i1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'j1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'k1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'l1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'm1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'o1', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'a0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'b0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'c0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'd0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'f0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'g0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'h0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'i0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'j0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'k0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'l0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'm0', nome: 'John', decricao: 'Test', status: 'feito'},
  { _id: 'o0', nome: 'John', decricao: 'Test', status: 'feito'},
];
